### ISSUE TITLE
1.18.2 Request

### ISSUE THREAD

**Issue by DALE-GH** [haruww/simple-radio#5]
Hey there! Will there be plans for adding support/porting to 1.18.2 and also later versions? Lots of people besides me are after the ports. Let me know if you are still working on it! If not and with your permission I could fork and port the mod myself :)

`People asking for ports:`
- #2 
- https://www.curseforge.com/minecraft/mc-mods/simple-radio?comment=7

_Best Regards,_
_DALE_  👋 

**_Hardware Tech, Systems Admin, Java/Spigot Dev, Server Enthusiast_**
\  https://linktr.ee/dale_lt   ///   https://mc.daleinfo.me  /

**Comment by 301haru** [comment]
Hello, thank you for the request. sadly I have not much time to care about this mod these days. so you can freely port the mod to 1.18.2 or other, but you must not share the ported vesion of mod to the public by yourself. you can pull request changes from your fork.

**Comment by DALE-GH** [comment]
> Hello, thank you for the request. sadly I have not much time to care about this mod these days. so you can freely port the mod to 1.18.2 or other, but you must not share the ported vesion of mod to the public by yourself. you can pull request changes from your fork.

Hey thanks for the quick reply! That's no problem and was my plan anyways as its cleaner way of doing things. I was also planning to put you on the curseforge page as the author _(unless you wanted to add me as a contributor on the current page once its ported, **but its up to you**)_

_- DALE 👋_

**Comment by TraipsingShadow** [comment]
Sorry for hijacking this ticket, but if, say, DALE does indeed make a successful 1.19.2+ port and is not allowed to share it, how would we, the "General Public", have access to it? Is there a separate license or arrangement that could be made that we can have access to it?

Apologies if this is not the right venue but there is no where else to talk about this particular add on.

**Comment by 301haru** [comment]
there's no problem. it will be uploaded on Curseforge site.
It only means DALE can't share the mod _by himself_ because it contains my original 1.16.5 code and it's infringement of my copyright

**Comment by 301haru** [comment]
@DALE-GH hey dale how are you. Seems like your port project getting delayed, I'll close this issue within 7 days if you don't reply, and I am going to make a port version of 1.16.5 because now I have some free time to start with.
